## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np

arr1 = np.arange(10, 41)
arr2 = np.arange(220, 251)

result_arr = arr1 + arr2
result_arr

array([230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290])

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [2]:
new_arr = np.arange(100,170).reshape(10,7)
new_arr

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [3]:
numbers = np.arange(1,51)
evens = numbers[numbers % 2 == 0]
odds = numbers[numbers % 2 == 1]
numbers2 = evens*odds
numbers2

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [4]:
new_array = np.random.randint(1000, size=(40,5))
new_array[(new_array % 2 == 0) & (new_array % 5 == 0)]

array([860, 330, 750, 550, 820, 970,  30,  20, 710, 410, 830, 690, 290,
       550, 570,  90, 210, 280,  90, 160, 760])